import { libreFranklin } from '@/fonts';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: 'Coming Soon!',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      dir='ltr'>
      <body className={libreFranklin.className}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
